Industry.create(name: "Tech")
Industry.create(name: "Medicine")
Industry.create(name: "Finance")
Industry.create(name: "Design")

#8 mentors
User.create(email: "mentor 1@email.com", role: 1, password: "password")
User.create(email: "mentor 2@email.com", role: 1, password: "password")
User.create(email: "mentor 3@email.com", role: 1, password: "password")
User.create(email: "mentor 4@email.com", role: 1, password: "password")
User.create(email: "mentor 5@email.com", role: 1, password: "password")
User.create(email: "mentor 6@email.com", role: 1, password: "password")
User.create(email: "mentor 7@email.com", role: 1, password: "password")
User.create(email: "mentor 8@email.com", role: 1, password: "password")
#10 mentees
User.create(email: "mentee 1@email.com", role: 2, password: "password")
User.create(email: "mentee 2@email.com", role: 2, password: "password")
User.create(email: "mentee 3@email.com", role: 2, password: "password")
User.create(email: "mentee 4@email.com", role: 2, password: "password")
User.create(email: "mentee 5@email.com", role: 2, password: "password")
User.create(email: "mentee 6@email.com", role: 2, password: "password")
User.create(email: "mentee 7@email.com", role: 2, password: "password")
User.create(email: "mentee 8@email.com", role: 2, password: "password")
User.create(email: "mentee 9@email.com", role: 2, password: "password")
User.create(email: "mentee 1@email.com0", role: 2, password: "password")
