Industry.create(name: "Tech")
Industry.create(name: "Medicine")
Industry.create(name: "Finance")
Industry.create(name: "Design")


User.create(email: "mentor1@email.com", role: 1, password: "password", industry_id: 1, concentration: "Full Stack Development", expertise: "Rails", first_name: "Leroy", last_name: "Barnes")
User.create(email: "mentor2@email.com", role: 1, password: "password", industry_id: 1, concentration: "Front End Development", expertise: "Design, UI", first_name: "Brian", last_name: "Greenway")
User.create(email: "mentor3@email.com", role: 1, password: "password", industry_id: 1, concentration: "Back End Development", expertise: "Databases", first_name: "Angela", last_name: "Wilkes")
User.create(email: "mentor4@email.com", role: 1, password: "password", industry_id: 2, concentration: "Anesthesiology", expertise: "Intubation", first_name: "George", last_name: "Olsson")
User.create(email: "mentor5@email.com", role: 1, password: "password", industry_id: 3, concentration: "Scaling Businesses", expertise: "Venture Capital", first_name: "Sandra", last_name: "Iselin")
User.create(email: "mentor6@email.com", role: 1, password: "password", industry_id: 3, concentration: "Network Growth", expertise: "Relationship Building", first_name: "Lindsay", last_name: "Lime")
User.create(email: "mentor7@email.com", role: 1, password: "password", industry_id: 4, concentration: "Graphic Design", expertise: "Adobe", first_name: "Bugs", last_name: "Bunny")
User.create(email: "mentor8@email.com", role: 1, password: "password", industry_id: 4, concentration: "Editorial Design", expertise: "Typography", first_name: "Happy", last_name: "Gilmore")
User.create(email: "mentee1@email.com", role: 2, password: "password", industry_id: 1, concentration: "Full Stack Development", first_name: "Arnold", last_name: "Palmer")
User.create(email: "mentee2@email.com", role: 2, password: "password", industry_id: 1, concentration: "Full Stack Development", first_name: "Avi", last_name: "Flombaum")
User.create(email: "mentee3@email.com", role: 2, password: "password", industry_id: 1, concentration: "Front End Development", first_name: "Ash", last_name: "Mormon")
User.create(email: "mentee4@email.com", role: 2, password: "password", industry_id: 2, concentration: "Medical Student", first_name: "Darth", last_name: "Vader")
User.create(email: "mentee5@email.com", role: 2, password: "password", industry_id: 2, concentration: "Nursing", first_name: "Jack", last_name: "Torrence")
User.create(email: "mentee6@email.com", role: 2, password: "password", industry_id: 3, concentration: "Accounting", first_name: "Ace", last_name: "Ventura")
User.create(email: "mentee7@email.com", role: 2, password: "password", industry_id: 3, concentration: "Banking", first_name: "John", last_name: "Malkovich")
User.create(email: "mentee8@email.com", role: 2, password: "password", industry_id: 4, concentration: "Graphic Design", first_name: "Raymond", last_name: "Babbitt")
User.create(email: "mentee9@email.com", role: 2, password: "password", industry_id: 4, concentration: "Graphic Design", first_name: "Sam", last_name: "Spade")
User.create(email: "mentee10@email.com", role: 2, password: "password", industry_id: 4,concentration: "Graphic Design",  first_name: "Tony", last_name: "Manero")
